import type { Property } from "@/types/property";

export const sampleProperties: Property[] = [
  {
    id: "1",
    code: "CD-101",
    title: "Casa térrea com suíte e piscina",
    slug: "casa-terrea-suite-piscina",
    description:
      "Ambientes integrados, área gourmet e acabamento contemporâneo em bairro tranquilo.",
    purpose: "SALE",
    type: "HOUSE",
    priceInCents: 79000000,
    areaM2: 116,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpots: 2,
    isCondo: false,
    isFeatured: true,
    isLaunch: false,
    addressSummary: "Jardim Bom Sucesso, Indaiatuba-SP",
    city: "Indaiatuba",
    district: "Jardim Bom Sucesso",
    community: null,
    images: [
      {
        id: "1a",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80",
        alt: "Fachada de casa contemporânea",
      },
    ],
  },
  {
    id: "2",
    code: "CD-202",
    title: "Casa de condomínio com projeto autoral",
    slug: "casa-condominio-projeto-autoral",
    description:
      "Living amplo, pé-direito alto, cozinha planejada e área externa para receber.",
    purpose: "SALE",
    type: "CONDO_HOUSE",
    priceInCents: 219000000,
    condoFeeCents: 36600,
    areaM2: 340,
    bedrooms: 3,
    bathrooms: 4,
    parkingSpots: 2,
    isCondo: true,
    isFeatured: true,
    isLaunch: false,
    addressSummary: "Jardim Esplanada, Indaiatuba-SP",
    city: "Indaiatuba",
    district: "Jardim Esplanada",
    community: "Residencial London Park",
    images: [
      {
        id: "2a",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80",
        alt: "Sala integrada de casa em condomínio",
      },
    ],
  },
  {
    id: "3",
    code: "CD-303",
    title: "Apartamento novo perto de servicos",
    slug: "apartamento-novo-perto-de-servicos",
    description:
      "Planta inteligente, varanda gourmet e lazer completo para rotina prática.",
    purpose: "SALE",
    type: "APARTMENT",
    priceInCents: 53000000,
    condoFeeCents: 42000,
    areaM2: 74,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 2,
    isCondo: true,
    isFeatured: false,
    isLaunch: true,
    addressSummary: "Vila Sfeir, Indaiatuba-SP",
    city: "Indaiatuba",
    district: "Vila Sfeir",
    community: "Viva Parque Sense",
    images: [
      {
        id: "3a",
        url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80",
        alt: "Apartamento com sala iluminada",
      },
    ],
  },
  {
    id: "4",
    code: "CD-404",
    title: "Casa mobiliada para locação",
    slug: "casa-mobiliada-para-locacao",
    description:
      "Residência completa em condomínio fechado, pronta para morar com conforto.",
    purpose: "RENT",
    type: "CONDO_HOUSE",
    priceInCents: 1700000,
    condoFeeCents: 112500,
    areaM2: 362,
    bedrooms: 4,
    bathrooms: 6,
    parkingSpots: 2,
    isCondo: true,
    isFeatured: true,
    isLaunch: false,
    addressSummary: "Jardim Vila Paradiso, Indaiatuba-SP",
    city: "Indaiatuba",
    district: "Jardim Vila Paradiso",
    community: "Jardim Vila Paradiso",
    images: [
      {
        id: "4a",
        url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1400&q=80",
        alt: "Casa de alto padrão em condomínio",
      },
    ],
  },
  {
    id: "5",
    code: "CD-505",
    title: "Galpão comercial com doca",
    slug: "galpao-comercial-com-doca",
    description:
      "Pé-direito alto, área administrativa e acesso fácil para operações comerciais.",
    purpose: "RENT",
    type: "COMMERCIAL",
    priceInCents: 2000000,
    areaM2: 935,
    bedrooms: null,
    bathrooms: 4,
    parkingSpots: 6,
    isCondo: false,
    isFeatured: false,
    isLaunch: false,
    addressSummary: "Jardim Alice, Indaiatuba-SP",
    city: "Indaiatuba",
    district: "Jardim Alice",
    community: null,
    images: [
      {
        id: "5a",
        url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1400&q=80",
        alt: "Galpão comercial amplo",
      },
    ],
  },
  {
    id: "6",
    code: "CD-606",
    title: "Lançamento com lazer completo",
    slug: "lancamento-com-lazer-completo",
    description:
      "Novo empreendimento com plantas compactas, lazer moderno e excelente potencial.",
    purpose: "SALE",
    type: "APARTMENT",
    priceInCents: 39000000,
    condoFeeCents: 28000,
    areaM2: 48,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    isCondo: true,
    isFeatured: false,
    isLaunch: true,
    addressSummary: "Parque Residencial Indaia, Indaiatuba-SP",
    city: "Indaiatuba",
    district: "Parque Residencial Indaia",
    community: "Grand Garden Residence",
    images: [
      {
        id: "6a",
        url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=80",
        alt: "Prédio residencial moderno",
      },
    ],
  },
];
